version: '3.8'
services:
  main:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - laravel-network

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: ${APP_NAME}-database
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}-redis
    command: /bin/sh -c "redis-server --requirepass $REDIS_PASSWORD"
    ports:
      - "63790:6379"
    restart: always
    networks:
      - laravel-network


volumes:
  db:
    driver: local
networks:
  laravel-network:
    driver: bridge