<?php

namespace App\Facade;

use Illuminate\Support\Facades\Facade;

class Param extends Facade
{
    protected static function getFacadeAccessor()
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}